### ISSUE TITLE
Broken mongoid dependencies

### ISSUE THREAD

**Issue by raphaelcm** [bowsersenior/workflow_on_mongoid#10]
in `workflow_on_mongoid.gemspec':

``` ruby
if RUBY_VERSION < '1.9.3' # Mongoid 3.x only works on ruby 1.9.3 and above
  s.add_dependency "mongoid", '~>2.0.0'
else
  s.add_dependency "mongoid", '~>3.0.0'
end
```

This means that the gem ONLY works with mongoid versions 2.0.X and 3.0.X.  Obviously it should also work with mongoid 2.X and Mongoid 3.X (3.1 will be out soon).

The dependency should be:

``` ruby
s.add_dependency "mongoid", '=>2.0.0'
```

**Comment by bowsersenior** [comment]
Thanks for reporting this! Let me have a look and fix this.

-Mani

**Comment by bowsersenior** [comment]
Should be fixed now. Pushed a new version of the gem:
- http://rubygems.org/gems/workflow_on_mongoid/versions/0.8.0.7

Let me know if you run into any more issues.
